version: "3"

services:
  # App (アプリケーション)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/grandcolline/clean-arch-demo:cached
      # --- exclude volums ---
      - /go/src/github.com/grandcolline/clean-arch-demo/.docker/
      - /go/src/github.com/grandcolline/clean-arch-demo/.git/
    ports:
      - 8080:8080
    depends_on:
      - mysql

  # MySQL (データベース)
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: app
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql:cached
      #- ./.docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
